### ISSUE TITLE
Results on Imagenet

### ISSUE THREAD

**Issue by asanakoy** [untitled-ai/self_supervised#10]
Hey,
Thanks for such a nice repo.
Have you trained on Imagenet? Do you get performance close to the reported in the paper (72.5%)?
Will the performance decrease a lot if we train only on 1 GPU?

Thanks!

**Comment by abefetterman** [comment]
Thanks for the comment! We did not get a chance to train BYOL on imagenet, but we did train MoCo and got similar results to the authors there. Good luck!
