### ISSUE TITLE
the dataset problem

### ISSUE THREAD

**Issue by cuixianheng** [untitled-ai/self_supervised#4]
when i run the code, i fund the data  load is error, can you tell me where the dataset in the code

**Comment by abefetterman** [comment]
Hi @cuixianheng 

Can you tell me more about how you tried to run this? If you are using `dataset_name = "stl10"`, the code will try to download to the folder specified in the environment variable `DATA_PATH`. If using `dataset_name = "imagenet"`, that path will need to already contain a folder containing the imagenet data.

**Comment by cuixianheng** [comment]
i am so sorry, the runing code is blow:

os.environ["DATA_PATH"] = "/root/data/cuixianheng/self_supervised/image/"
model = MoCoMethod()
trainer = pl.Trainer(gpus=1, max_epochs=200)
trainer.fit(model)
trainer.save_checkpoint("example.ckpt")

i want to training my own data, can you  tell me what should i do?

**Comment by cuixianheng** [comment]
> Hi @cuixianheng
> 
> Can you tell me more about how you tried to run this? If you are using `dataset_name = "stl10"`, the code will try to download to the folder specified in the environment variable `DATA_PATH`. If using `dataset_name = "imagenet"`, that path will need to already contain a folder containing the imagenet data.

**Comment by cuixianheng** [comment]
> Hi @cuixianheng
> 
> Can you tell me more about how you tried to run this? If you are using `dataset_name = "stl10"`, the code will try to download to the folder specified in the environment variable `DATA_PATH`. If using `dataset_name = "imagenet"`, that path will need to already contain a folder containing the imagenet data.


i am so sorry, the runing code is blow:

os.environ["DATA_PATH"] = "/root/data/cuixianheng/self_supervised/image/"
model = MoCoMethod()
trainer = pl.Trainer(gpus=1, max_epochs=200)
trainer.fit(model)
trainer.save_checkpoint("example.ckpt")

i want to training my own data, can you tell me what should i do?
